### PR TITLE
Pre-editing for translation

### PR DESCRIPTION
**Pull request by majamanojlovic**

### CODE REVIEW

**Comment by majamanojlovic** [comment]
Hi @sra405 there are some leftover commits here and a conflict in a file I don't recognise. Not sure if this is something you worked on?

**Comment by sra405** [comment]
> Hi @sra405 there are some leftover commits here and a conflict in a file I don't recognise. Not sure if this is something you worked on?

Apologies, I was part way through updating these files and kept hitting rate limits stopping people from building 😅 so I paused it! Sorry if that caused any confusion.

**Comment by majamanojlovic** [comment]
> > Hi @sra405 there are some leftover commits here and a conflict in a file I don't recognise. Not sure if this is something you worked on?
> 
> Apologies, I was part way through updating these files and kept hitting rate limits stopping people from building 😅 so I paused it! Sorry if that caused any confusion.

No worries! Am I ok to merge then?

**Comment by sra405** [comment]
> No worries! Am I ok to merge then?

Yep, it looks a little suspect but it's fine 👍

**Pull request merged**
